image:          php:7.1-alpine

before_script:
  - apk update
  - apk add git
  - docker-php-ext-install pdo pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

test:
  script:
    - php composer.phar test
