language:          php

php:
  - 7.1
  - 7.2

install:           composer install

dist:              trusty

sudo:              required

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql_upgrade
  - sudo service mysql restart

before_script:
  - mysql -e 'create database phpunit;'
